// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbecyujvzfaxldmijbgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZWN5dWp2emZheGxkbWlqYmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDUwNTQsImV4cCI6MjA2NTY4MTA1NH0.oY-gTTrIPeOCWDR-tsI3nLRXMNoBBQPqnDpkklc5oa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);